
name: main
on: [push, pull_request]

jobs:
  # We use "o" as the name to keep it short since the flavor repeats
  # it, and the current actions interface doesn't show very many
  # characters in the test names.
  o:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        flavor:
          - core+ext/openjdk11/pg-11
          - core+ext/openjdk11/pg-14

          # integration
          - int/openjdk11/pup-6.x/srv-6.x/pg-11/rich
          - int/openjdk11/pup-7.x/srv-7.x/pg-11/rich

          - rspec/pup-7.x
          - lint/openjdk11

        os: [ubuntu-20.04]

        # Defaults for special-case influencing vars
        lein-profile: ['']
        drop-joins: ['']
        deprecated-query-streaming: ['']

        # Special cases
        include:
          - os: macos-10.15
            flavor: core+ext/openjdk11/pg-11
          - os: macos-10.15
            flavor: int/openjdk11/pup-7.x/srv-7.x/pg-11/rich
          - os: macos-10.15
            flavor: rspec/pup-7.x

    steps:
      - name: Compute job outputs
        id: computed
        run: |
          echo "::set-output name=day::$(date +%Y-%m-%d)"
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/cache@v2
        with:
          key: |
            ${{ matrix.flavor }}
            ${{ runner.os }}
            ${{ hashFiles('**/Gemfile') }}
            ${{ hashFiles('**/project.clj') }}
            ${{ steps.computed.outputs.day }}
          path: |
            ci/local/jdk
            vendor/bundle/ruby
            ~/.m2/repository
            ~/Library/Caches/Homebrew
      - name: Gather inital host info
        run: ext/bin/host-info
      - env:
          LEIN_PROFILES: ${{ matrix.lein-profile }}
          PDB_QUERY_OPTIMIZE_DROP_UNUSED_JOINS: ${{ matrix.drop-joins }}
          PDB_USE_DEPRECATED_QUERY_STREAMING_METHOD: ${{ matrix.deprecated-query-streaming }}
        run: ci/bin/prep-and-run-in github ${{ matrix.flavor }}
