name: scan ruby with snyk
on:
  push:
    branches:
      - 6.x
      - main
jobs:
  snyk_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_PE_TOKEN }}
        with:
          command: monitor
          args: --org=puppet-enterprise --project-name=puppetlabs/puppetdb
